name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Ensure this matches your project's target framework (e.g., '8.0.x')

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Blazor WebAssembly App
      # Output directly to a 'publish-output' folder in the root of the runner's workspace
      run: dotnet publish -c Release -o publish-output --nologo /p:GITHUB_PAGES=true

    - name: Change base-href in index.html
      # The index.html is actually located inside 'publish-output/wwwroot/{YourProjectName}/'
      run: |
        sed -i 's|<base href="/" />|<base href="/Mathletes-Companion/" />|g' publish-output/wwwroot/Mathletes-Companion/index.html
        # IMPORTANT: Replace /Mathletes-Companion.Client/ with your exact GitHub repository name!
        # And confirm 'Mathletes-Companion.Client' after 'wwwroot/' also matches your actual project name.

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # The directory to publish is now 'publish-output/wwwroot/{YourProjectName}'
        publish_dir: ./publish-output/wwwroot/Mathletes-Companion
        # cname: yourdomain.com # Uncomment and replace with your custom domain if you have one
                                # Otherwise, keep it commented out